services:
  backend:
    build: ./backend
    command: ./start.sh
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  frontend:
    build:
      context: ./frontend      
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development    

volumes:
  postgres_data:
  node_modules: