# Generated by Django 5.1.1 on 2024-09-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
